### ISSUE TITLE
URL encoding issue on links

### ISSUE THREAD

**Issue by fulldecent** [BrandonXLF/linkcount#10]
This page has direct links to search Wikipedia:

<img width="1252" alt="Screen Shot 2022-02-07 at 14 53 19" src="https://user-images.githubusercontent.com/382183/152861758-3fa2602d-691f-4f23-95d8-199ecdc9745b.png">

But the links are broken:

<img width="1252" alt="Screen Shot 2022-02-07 at 14 52 54" src="https://user-images.githubusercontent.com/382183/152861674-3faca2bc-3b01-4e1b-b2cc-0d20d4d83158.png">

The correct way to do this is to encode spaces as `%20` rather than `+`.

**Comment by BrandonXLF** [comment]
Thank you for the issue and pull request. I have now updated the Toolforge server with your change.

**Comment by fulldecent** [comment]
You're welcome. Wow we are live!
