### ISSUE TITLE
What is Included in Backlinks?

### ISSUE THREAD

**Issue by cdr4321** [BrandonXLF/linkcount#16]
Love this tool. But I'm a bit confused by some results. When I look up backlinks for Jay-Z, it lists [LL Cool J](https://en.wikipedia.org/wiki/LL_Cool_J) as a backlink. Yet when I go to [LL Cool J](https://en.wikipedia.org/wiki/LL_Cool_J)'s Wikipedia page, I can't find any link to Jay-Z's page. What exactly does it mean to be a backlink? How do you just find direct links?

**Comment by BrandonXLF** [comment]
The backlink count is based on the final wikitext of the article, after all templates are transcluded. In this case, Jay-Z is linked to in LL Cool J by the [Template:Grammy Award for Best Rap Solo Performance](https://en.wikipedia.org/wiki/Template:Grammy_Award_for_Best_Rap_Solo_Performance) template. 

The tool is currently unable to differentiate from a link on the page and a link via a template, see #9.
