### ISSUE TITLE
Browser back/forward doesn't work after opening a deep link

### ISSUE THREAD

**Issue by nardog** [BrandonXLF/linkcount#26]
Steps to reproduce:

- Open the link count for a specific page via a URL, e.g. https://linkcount.toolforge.org/?project=en.wikipedia.org&page=Main%20Page
- Modify and submit the form
- Use the browser's "Go back" feature

Actual behavior: The page doesn't change.

Expected behavior: The results for the original query are shown.

**Comment by ThreatLEVELred** [comment]
Forked
