### ISSUE TITLE
`hideredirs=1` is missing in the links "Wikilinks" and "Transclusions".

### ISSUE THREAD

**Issue by Ashleycho35** [BrandonXLF/linkcount#5]
`hideredirs=1` is missing in the links "Wikilinks" and "Transclusions".

__Originally posted by @nardog in https://github.com/BrandonXLF/linkcount/issues/1__

**Comment by BrandonXLF** [comment]
Duplicate of #1. I might add it, but I'd like to find an option that will still allow indirect links to be viewed.

**Comment by abirfo1** [comment]
****
